### ISSUE TITLE
Create component with several konva elements

### ISSUE THREAD

**Issue by kagemusha** [mjanjic01/ember-konva#2]
Is it possible to create a component which encapsulates several konva elements that can be added to a Stage or Layer in an hbs template?  Been trying to figure this out without luck.

**Comment by mjanjic01** [comment]
Hi @kagemusha ,
there are two approaches to this I have been working with recently:

1. Create a glimmer or ember component which recieves the child components API via a component argument (`@parent` in this example):
```hbs
{{!-- example-component/template.hbs --}}
<@parent.Rect @x={{10}} @y={{20}} @fill="red" />
<@parent.Text @text="Hello world" />
```

then invoke it as:
```hbs
<Konva::Stage as |Stage|>
  <Stage.Layer as |Layer|>
    <ExampleComponent @parent={{Layer}} />
  </Stage.Layer>
</Konva::Stage>
```

2. Extend the `konva-component`

```js
import Konva from 'konva';
import KonvaComponent from 'ember-konva/components/konva';

export default ExampleComponent extends KonvaComponent {
  constructor() {
    super(Konva.Group, ...arguments);
  }
}
```

```hbs
{{!-- everything in this template is a direct child of the Group instantiated in the constructor --}}
<Konva::Rect @parent={{this.konvaNode}} @x={{10}} @y={{20}} @fill="red" />
<Konva::Text @parent={{this.konvaNode}}  @text="Hello world" />
```

At the moment I use the first approach since it allows service injection in the component (i'm working on a fix to allow this in konva components also) and more predictable handling of component arguments, since `this.args` is not updated in a konva component (you would have to hook into the `setProperties` method on the instance)

**Comment by kagemusha** [comment]
Thanks!  Works perfectly.

I thought I tried something like that, but must have left something out.  

If you'd like I can add an example of this to the dummy app and submit a PR

**Comment by mjanjic01** [comment]
No problem, I'm glad you're finding your way 😄 

> If you'd like I can add an example of this to the dummy app and submit a PR

Sure that would be awesome!

**Comment by kagemusha** [comment]
Add a prelim PR #3

Would be nice to make the whole component draggable so perhaps you could advise me on that

**Comment by mjanjic01** [comment]
Awesome, I will close this and move the discussion there then. Thanks!
